### PR TITLE
Add documentation about test helpers

### PR DESCRIPTION
**Pull request by ChrisBr**
While working the streamy events I found out that there is no documentation about the test helpers which I add now.

### CODE REVIEW

**Comment by ChrisBr** [comment]
@balvig what do you want me to say with the link? That RSpec and Minitest helpers behave slightly different? Or that ``assert_published_event`` as well? Can you please elaborate 😄

**Comment by dannyd4315** [comment]
@ChrisBr I am going to be updating the test helpers for minitest so the rspec/minitest helpers function the same way. Leave that with me today and then we can get this merged in 👍 🙇

**Comment by dannyd4315** [comment]
@ChrisBr Do you want to merge this and I will update with the test documentation?

**Comment by ChrisBr** [comment]
Cheers @dannyd4315

**Pull request merged**
