### PR TITLE
Fix rubocop config

### PR DESCRIPTION
**Pull request by jesseclark**
Some outdated configuration directives were preventing Rubocop from running. This is the error that was being generated:
```
Error:Rubocop returned exit code: 2
stderr:
.rubocop.yml: Style/FlipFlop has the wrong namespace - should be Lint
Error: obsolete `EnforcedStyle: rails` (for Layout/IndentationConsistency) found in .rubocop.yml
`EnforcedStyle: rails` has been renamed to `EnforcedStyle: indented_internal_methods`
```

This PR updates `.rubocop.yml` so it will run again.

### CODE REVIEW

**Comment by ChrisBr** [comment]
We could use our global style guide instead?

```
inherit_from:
  - https://raw.githubusercontent.com/cookpad/global-style-guides/master/.rubocop.yml
```

**Comment by jesseclark** [comment]
> We could use our global style guide instead?
> 
> ```yaml
> inherit_from:
>   - https://raw.githubusercontent.com/cookpad/global-style-guides/master/.rubocop.yml
> ```

It looks like this was happening [once upon a time](https://github.com/cookpad/streamy/commit/e089fea24ab6f6b1014de647e4af5a8b8b38b0f5) but was [later removed](https://github.com/cookpad/streamy/commit/1cafdb5b8d863653159e08c3f0f4b221a863de7c#diff-11a0d7906801d9dea0eccb85667ad811) because remote inheritence didn't play nice with Hound.

There was once [a test](https://github.com/cookpad/streamy/blob/1cafdb5b8d863653159e08c3f0f4b221a863de7c/test/rubocop_config_test.rb) that made sure the local file stayed in sync with the global-web remote but it has since been removed.

I've gone ahead and added a commit that syncs the `.rubocop.yml` from global-web. This situation seems less than ideal going forward though. We could consider extracting out our global-web rubocop config into a gem that could be used in other projects and that might work better with Hound. Or we could consider changing to whatever linting mechanism we are using in global-web and maybe that will work with the remote inheritence where Hound would not. Or we could re-add the test that ensures the files are synced.

@balvig Do you have any background knowledge of when/why that test was removed or thoughts about how to proceed.

I was shooting for a quick-fix to get rubocop running here. Maybe we could create a low-priority issue or kaizen task for whichever solution we think it best for the long term?

**Comment by jesseclark** [comment]
FWIW, I just realized that `Error:Rubocop returned exit code: 2` means that rubocop still executed it was just returning warnings. Still might be worth it to merge the sync from global-style-guides though as a quick-fix for style guide consistency.

**Comment by balvig** [comment]
@jesseclark Ah...this looks like a relic from back when we were using HoundCI for all things linting (we don't anymore!)

Since Rubocop linting only happens locally for this project (until we add it to CircleCI as for global-web), indeed I believe all we should need in the config file is the `inherited_from` bit.

(Looks like we can then also remove the `.hound` and `.travis` files!)

**Comment by jesseclark** [comment]
> @jesseclark Ah...this looks like a relic from back when we were using HoundCI for all things linting (we don't anymore!)
> 
> Since Rubocop linting only happens locally for this project (until we add it to CircleCI as for global-web), indeed I believe all we should need in the config file is the `inherited_from` bit.
> 
> (Looks like we can then also remove the `.hound` and `.travis` files!)

Thanks for clarifying 👍 . I will remove those config files you mentioned and switch back to `inherited_from`.

**Pull request merged**
